export const UPLOAD_VIDEO_REQUEST = "UPLOAD_VIDEO_REQUEST";
export const UPLOAD_VIDEO_SUCCESS = "UPLOAD_VIDEO_SUCCESS";
export const UPLOAD_VIDEO_FAIL = "UPLOAD_VIDEO_FAIL";

export const CREATE_SUBTITLE_REQUEST = "CREATE_SUBTITLE_REQUEST";
export const CREATE_SUBTITLE_SUCCESS = "CREATE_SUBTITLE_SUCCESS";
export const CREATE_SUBTITLE_FAIL = "CREATE_SUBTITLE_FAIL";

// export const FETCH_SUBTITLE_REQUEST = "FETCH_SUBTITLE_REQUEST";
// export const FETCH_SUBTITLE_SUCCESS = "FETCH_SUBTITLE_SUCCESS";
// export const FETCH_SUBTITLE_FAIL = "FETCH_SUBTITLE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
